use test

INSERT INTO tabla1( FECHA_ACTUALIZACION,ENTIDAD_RES,FECHA_SINTOMAS,FECHA_DEF,RESULTADO )
SELECT FECHA_ACTUALIZACION,ENTIDAD_RES,FECHA_SINTOMAS,FECHA_DEF,RESULTADO FROM Data_bi
WHERE RESULTADO = '1' and ENTIDAD_RES = '26'




INSERT INTO tabla2(ENTIDAD_RES,TIPO_PACIENTE,FECHA_INGRESO)
SELECT ENTIDAD_RES,TIPO_PACIENTE,FECHA_INGRESO FROM Data_bi
WHERE ((TIPO_PACIENTE = '2' and ENTIDAD_RES = '26') or (TIPO_PACIENTE = '2' and ENTIDAD_RES = '21') or (TIPO_PACIENTE = '2' and ENTIDAD_RES = '19') or (TIPO_PACIENTE = '2' and ENTIDAD_RES = '8'))